// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEooBv_alHXK64PsgzGROzqksuLgr0xeU',
    appId: '1:539073860771:android:e60e49ca0d7538c4b09b16',
    messagingSenderId: '539073860771',
    projectId: 'xpensemate-d34e2',
    storageBucket: 'xpensemate-d34e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKWhAGc9Votb66yZ0If4mPGT_lp-fEjX4',
    appId: '1:539073860771:ios:2a67e68bd4540793b09b16',
    messagingSenderId: '539073860771',
    projectId: 'xpensemate-d34e2',
    storageBucket: 'xpensemate-d34e2.firebasestorage.app',
    androidClientId: '539073860771-rjqkau5527kakifsbkmj4dmosus5247b.apps.googleusercontent.com',
    iosClientId: '539073860771-m9p094jthghcmus84ptrqqaidlj86jjm.apps.googleusercontent.com',
    iosBundleId: 'com.example.xpensemate',
  );

}